name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main    # 當 main 有 push 時自動觸發

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          # 範例：把 GitHub Secret 注入給 build 過程
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist           # Vite 的輸出資料夾；CRA 是 build
          publish_branch: gh-pages
